'use strict';
/**
 * Starting with Windows, silently.
 *
 * Two things used to make the boot noisy:
 *
 *  1. The app shipped with requestedExecutionLevel "highestAvailable", so every
 *     single launch — including the one at logon — raised a UAC prompt. Nothing
 *     the panel does needs administrator rights: it writes to the per-user
 *     app-data folder and the user's own home, spawns node and cloudflared as
 *     the user, and binds ports above 1024. That is fixed in package.json.
 *
 *  2. Autostart was configured twice — a Startup-folder script AND an
 *     Electron login item — so two copies launched at logon. The single-instance
 *     lock let one win, but the loser still poked the winner, which un-hid the
 *     window. One mechanism only, and the survivor stays hidden.
 *
 * The script itself is built here so it can be tested without Electron.
 */
const path = require('node:path');

const SCRIPT_NAME = 'NimbusDriveAutoStart.vbs';

/** Where Windows looks for per-user startup items. */
function startupDir(appData) {
  return path.join(appData || '', 'Microsoft', 'Windows', 'Start Menu', 'Programs', 'Startup');
}
function startupScriptPath(appData) {
  return path.join(startupDir(appData), SCRIPT_NAME);
}

/**
 * A .vbs wrapper is used rather than a shortcut because WScript.Shell.Run with
 * window style 0 starts the process with no console flash at all.
 *
 * VBScript has no backslash escapes — a path must go in verbatim, and only the
 * double quotes need doubling. Escaping backslashes (as this once did) produced
 * C:\\Users\\… inside the script, which Windows only tolerated by accident.
 */
function buildStartupScript(exePath, args = ['--hidden', '--autostart']) {
  const quoted = `"${String(exePath).replace(/"/g, '""')}"`;
  const tail = args.length ? ` ${args.join(' ')}` : '';
  return [
    "' Generated by Nimbus Drive — starts the drive at logon with no window.",
    '\' Delete this file, or turn the setting off in the app, to stop it.',
    'Set WshShell = CreateObject("WScript.Shell")',
    `WshShell.Run "${quoted.replace(/"/g, '""')}${tail}", 0, False`,
    '',
  ].join('\r\n');
}

/**
 * Create or remove the startup entry.
 * @returns {{ok:boolean, path:string, action:'created'|'removed'|'absent', error?:string}}
 */
function applyWindowsStartup({ appData, exePath, enable, fs }) {
  const target = startupScriptPath(appData);
  try {
    if (enable) {
      fs.mkdirSync(startupDir(appData), { recursive: true });
      fs.writeFileSync(target, buildStartupScript(exePath), 'utf8');
      return { ok: true, path: target, action: 'created' };
    }
    if (fs.existsSync(target)) {
      fs.unlinkSync(target);
      return { ok: true, path: target, action: 'removed' };
    }
    return { ok: true, path: target, action: 'absent' };
  } catch (err) {
    return { ok: false, path: target, action: enable ? 'created' : 'removed', error: err.message };
  }
}

/** Was this process launched by the autostart entry (rather than by a person)? */
function isAutostartLaunch(argv = []) {
  return argv.includes('--hidden') || argv.includes('--autostart');
}

module.exports = { SCRIPT_NAME, startupDir, startupScriptPath, buildStartupScript, applyWindowsStartup, isAutostartLaunch };
