tunnel: 451d9ecf-d503-4309-bd3a-0974ee86a5e3
credentials-file: C:\Users\conta\.cloudflared\451d9ecf-d503-4309-bd3a-0974ee86a5e3.json

ingress:
  - hostname: cloud.moaazmustafa.dev
    service: http://localhost:3000
    originRequest:
      connectTimeout: 30s
      noTLSVerify: true
  - service: http_status:404
